require('plugin-config/telescope')
require('plugin-config/vimtex')
require('plugin-config/coc')
require('plugin-config/airline')
require('plugin-config/nvim-treesitter')
require('plugin-config/barbar')
require('plugin-config/runner')
