-- require('plugin-config/leaderf')
require('plugin-config/telescope')
require('plugin-config/asyncrun')
require('plugin-config/vimtex')
require('plugin-config/coc')
require('plugin-config/airline')
require('plugin-config/nvim-treesitter')
require('plugin-config/barbar')
